### PR TITLE
added description for each parameter

### PR DESCRIPTION
**Pull request by mustaphazorgati**

### CODE REVIEW

**Review by filipecorrea — APPROVED** [review]

**Comment by filipecorrea** [comment]
Hi @stevemar. I think I lost write access to this repo so I can't merge this pull request.

**Comment by stevemar** [comment]
@filipecorrea try again?

**Comment by mustaphazorgati** [comment]
That was easy @stevemar. Can I get write access too? :joy:

**Comment by mustaphazorgati** [comment]
Just kidding :)

**Comment by filipecorrea** [comment]
It's not working yet, @stevemar. Can you please double check?

**Comment by filipecorrea** [comment]
Nevermind, @stevemar. It worked after I accepted the invitation by mail.

**Pull request merged**
